server:
  port: 8086
spring:
  application:
    name: hystrix-feign
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
#      feign\u9ED8\u8BA4\u662F\u5173\u95EDhystrix,\u9700\u8981\u6253\u5F00
feign:
  hystrix:
    enabled: true