server:
  port: 8083
spring:
  application:
    name: server-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
#server-ribbon:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule