spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8092/
server:
  port: 8093
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka